title: <p align="center"> Manjit Singh </p>
#logo: /assets/img/picture.png

description:
  <br>
  **About Me**
  
  I'm Manjit, a postgraduate student in Data Science and AI specializing in NLP at IIIT Bangalore.
  I have experience in Machine Learning, Data Analytics, and AI, with expertise in Python, Deep Learning, and NLP using frameworks like TensorFlow and PyTorch.
  Previously, I worked at Quest Global Technologies Ltd, where I contributed to Business Analysis, Market Research, and Database Management.
  I'm passionate about using data-driven insights to solve complex problems and drive impactful results.
  Feel free to reach out at itsmanjit20@gmail.com for opportunities or inquiries!
  <br>
  </p>
  
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/manjitsinghindia/">LinkedIn</a> |
  <a href="https://github.com/ManjitSingh2003">GitHub</a>

theme: jekyll-theme-hacker
