title: Manjit Singh
# logo: /assets/img/picture.png

description: 
  <strong>About Me</strong>
  <br><br>
  Hi, I'm Manjit — a Data Analyst at <strong>Samhita</strong> and a postgraduate in <strong>Data Science and AI</strong> with a specialization in <strong>Natural Language Processing</strong> from IIIT Bangalore.
  <br><br>
  I work at the intersection of data, technology, and social impact — building dashboards, automating data workflows, and delivering insights from complex datasets. My toolkit includes Python, SQL, Power BI, Tableau and GenAI, along with hands-on experience in Machine Learning, NLP, and Deep Learning using frameworks like TensorFlow and PyTorch.
  <br><br>
  I’m passionate about using data to solve real-world problems and always curious to learn what’s next in AI and analytics.
  <br><br>
  Feel free to reach out at <a href="mailto:itsmanjit20@gmail.com" style="color:white;">itsmanjit20@gmail.com</a> for opportunities or just to connect!

  
  <p align="center">
  <a href="pdf/Manjit_Singh_Resume.pdf" style="color:white;">Resume</a> |
  <a href="https://www.linkedin.com/in/manjitsinghindia/" style="color:white;">LinkedIn</a> |
  <a href="https://github.com/ManjitSingh2003" style="color:white;">GitHub</a>
  </p>

theme: jekyll-theme-cayman



