title: Manjit Singh
# logo: /assets/img/picture.png

description: 
  <strong>About Me</strong><br><br>
  I'm Manjit, a Data Analyst at <strong>Samhita</strong> and a postgraduate in <strong>Data Science and AI (NLP specialization)</strong> from IIIT Bangalore.<br><br>
  I enjoy solving real-world problems with data, and my work focuses on:<br><br>
   • Machine Learning & Deep Learning<br>
   • Natural Language Processing (NLP)<br>
   • Generative AI and automation<br>
   • Data Visualization & Dashboarding<br>
   • SQL-based data analysis and reporting<br><br>
  I’m proficient in tools/libraries like <strong>Python, SQL, Power BI, Tableau, TensorFlow, PyTorch, NLTK</strong> and <strong>Keras</strong>.<br><br>
  Feel free to reach out at <a href="mailto:itsmanjit20@gmail.com" style="color:white;">itsmanjit20@gmail.com</a> for collaborations, opportunities, or just to chat!<br><br>
  <p align="center">
    <a href="pdf/Manjit_Singh_Resume.pdf" style="color:white;">Resume</a> |
    <a href="https://www.linkedin.com/in/manjitsinghindia/" style="color:white;">LinkedIn</a> |
    <a href="https://github.com/ManjitSingh2003" style="color:white;">GitHub</a>
  </p>

theme: jekyll-theme-cayman
